# Generated by Django 3.2 on 2021-04-18 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now=True)),
                ('end', models.DateTimeField(auto_now=True)),
                ('game_board_size', models.PositiveIntegerField()),
                ('gamer_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamer_1', to=settings.AUTH_USER_MODEL)),
                ('gamer_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamer_2', to=settings.AUTH_USER_MODEL)),
                ('loser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to=settings.AUTH_USER_MODEL)),
                ('winner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
