# Generated by Django 3.2 on 2021-04-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktaktoe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gamer_1',
            new_name='gamer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gamer_2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='loser',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.AddField(
            model_name='game',
            name='win',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
